
services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:17.6-alpine
    volumes:
      - ./vol/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env